MOUSEKEY_ENABLE = yes
SEND_STRING_ENABLE = yes
LAYER_LOCK_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = no
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no

VPATH += keyboards/gboards
